-- 13. Revenue by Customer (Medium)
-- Problem:
-- Calculate the total revenue generated by each customer in the past year. Include customer_id, name, and total_revenue.

-- Constraints:

-- Use the following schema:

-- customer, payment.
-- Combine first_name and last_name as name.

-- Only include payments made in the past year.

-- Sort by total_revenue in descending order.

-- Output:

-- customer_id	name	total_revenue
-- 145	John Doe	500.00
-- 302	Alice Johnson	450.00

-- ======================================================================================================================================
-- ======================================================================================================================================

with
    customer_revenue as (
        select
            customer_id,
            sum(amount) as total_revenue
        from
            payment
        where 
            payment_date >= date_sub((select max(payment_date) from payment), interval 12 month)
        group by
            customer_id
    )
select
    customer_id,
    concat(first_name, " ", last_name) as name,
    total_revenue
from
    customer c join customer_revenue cr using (customer_id)
order by
    total_revenue desc

-- optimized
with
    cutoff_date as (
        select date_sub(max(payment_date), interval 12 month) as cutoff
        from payment
    ),
    customer_revenue as (
        select
            customer_id,
            sum(amount) as total_revenue
        from
            payment join cutoff_date
        where 
            payment_date >= cutoff
        group by
            customer_id
    )
select
    customer_id,
    concat(first_name, " ", last_name) as name,
    total_revenue
from
    customer c join customer_revenue cr using (customer_id)
order by
    total_revenue desc
